const Map<String, String> upiApps = {
  'com.google.android.apps.nbu.paisa.user': 'Google Pay',
  'com.phonepe.app': 'PhonePe',
  'net.one97.paytm': 'PayTM',
  'in.amazon.mShop.android.shopping': 'Amazon Pay',
  'com.paytmmall': 'Paytm Mall',
  'in.org.npci.upiapp': 'BHIM',
  'com.csam.icici.bank.imobile': 'ICICI Imobile',
  'com.sbi.upi': 'SBI',
  'com.icicibank.pockets': 'ICICI Pockets',
  'com.snapwork.hdfc': 'HDFC Snapwork',
  'com.enstage.wibmo.hdfc': 'HDFC Wibmo',
  'com.upi.axispay': 'Axis Pay',
  'com.axis.mobile': 'Axis Mobile',
  'com.bankofbaroda.upi': 'Bank of Baroda',
  'com.fss.pnbpsp': 'PNB',
  'com.olive.kotak.upi': 'Kotak',
  'com.fss.idfcpsp': 'IDFC PSP',
  'com.YesBankABIPBL': 'Yes Bank',
  'com.upi.federalbank.org.lotza': 'Federal Bank',
  'com.mgs.induspsp': 'Indus Bank',
  'com.mgs.yesmerchantnative.prod': 'Yes Merchant',
  'com.instagram.android': 'Instagram',
};
